using Microsoft.EntityFrameworkCore;
using QuyNhaMinh.Api.Contracts;
using QuyNhaMinh.Api.Data;
using QuyNhaMinh.Api.Domain;
using QuyNhaMinh.Api.Services;

namespace QuyNhaMinh.Api.Endpoints;

public static class FinanceEndpoints {
    public static IEndpointRouteBuilder MapFinance(this IEndpointRouteBuilder app) {
        var api = app.MapGroup("/api/funds/{fundId:guid}").RequireAuthorization().RequireRateLimiting("api");
        api.MapGet("/categories", Categories).WithTags("Categories");
        api.MapPost("/categories", CreateCategory).WithTags("Categories");
        api.MapPut("/categories/{id:guid}", UpdateCategory).WithTags("Categories");
        api.MapDelete("/categories/{id:guid}", DeleteCategory).WithTags("Categories");
        api.MapGet("/accounts", Accounts).WithTags("Money accounts");
        api.MapPost("/accounts", CreateAccount).WithTags("Money accounts");
        api.MapPut("/accounts/{id:guid}", UpdateAccount).WithTags("Money accounts");
        api.MapDelete("/accounts/{id:guid}", DeleteAccount).WithTags("Money accounts");
        api.MapGet("/transactions", Transactions).WithTags("Transactions");
        api.MapPost("/transactions", CreateTransaction).WithTags("Transactions");
        api.MapPut("/transactions/{id:guid}", UpdateTransaction).WithTags("Transactions");
        api.MapDelete("/transactions/{id:guid}", DeleteTransaction).WithTags("Transactions");
        api.MapGet("/trash", Trash).WithTags("Backup and trash");
        api.MapPost("/trash/restore", Restore).WithTags("Backup and trash");
        api.MapDelete("/trash/{id:guid}/permanent", PermanentDelete).WithTags("Backup and trash");
        api.MapGet("/budgets", Budgets).WithTags("Budgets");
        api.MapPost("/budgets", UpsertBudget).WithTags("Budgets");
        api.MapDelete("/budgets/{id:guid}", DeleteBudget).WithTags("Budgets");
        api.MapGet("/reminders", Reminders).WithTags("Reminders");
        api.MapPost("/reminders", CreateReminder).WithTags("Reminders");
        api.MapPut("/reminders/{id:guid}", UpdateReminder).WithTags("Reminders");
        api.MapDelete("/reminders/{id:guid}", DeleteReminder).WithTags("Reminders");
        api.MapGet("/dashboard", Dashboard).WithTags("Dashboard and reports");
        api.MapGet("/reports", Report).WithTags("Dashboard and reports");
        return app;
    }

    static async Task<IResult> Categories(Guid fundId, string? type, FundAccess access, AppDb db) { await access.Require(fundId); var q = db.Categories.Where(x => x.FundId == fundId); if (!string.IsNullOrWhiteSpace(type)) q = q.Where(x => x.Type == type); return Results.Ok(await q.OrderBy(x => x.Type).ThenBy(x => x.Name).ToListAsync()); }
    static async Task<IResult> CreateCategory(Guid fundId, CategoryRequest x, FundAccess access, AppDb db) { await access.Require(fundId, Roles.Owner, Roles.Admin); var c = new QuyNhaMinh.Api.Domain.Category { FundId = fundId, Name = x.Name.Trim(), Type = x.Type, Icon = x.Icon, Color = x.Color }; db.Categories.Add(c); await db.SaveChangesAsync(); return Results.Created($"/api/funds/{fundId}/categories/{c.Id}", c); }
    static async Task<IResult> UpdateCategory(Guid fundId, Guid id, CategoryRequest x, FundAccess access, AppDb db) { await access.Require(fundId, Roles.Owner, Roles.Admin); var c = await db.Categories.SingleOrDefaultAsync(v => v.Id == id && v.FundId == fundId); if (c is null) return Results.NotFound(); c.Name = x.Name.Trim(); c.Type = x.Type; c.Icon = x.Icon; c.Color = x.Color; await db.SaveChangesAsync(); return Results.Ok(c); }
    static async Task<IResult> DeleteCategory(Guid fundId, Guid id, FundAccess access, CurrentUser user, AppDb db) { await access.Require(fundId, Roles.Owner, Roles.Admin); var c = await db.Categories.SingleOrDefaultAsync(v => v.Id == id && v.FundId == fundId); if (c is null) return Results.NotFound(); if (await db.Transactions.AnyAsync(t => t.CategoryId == id)) return Results.Conflict(new { message = "Danh mục đã có giao dịch; chỉ có thể ẩn." }); SoftDelete(c, user.Id); await db.SaveChangesAsync(); return Results.NoContent(); }

    static async Task<IResult> Accounts(Guid fundId, FundAccess access, AppDb db) { await access.Require(fundId); var data = await db.MoneyAccounts.Where(a => a.FundId == fundId).Select(a => new { a.Id, a.Name, a.Type, a.Currency, Balance = a.InitialBalance + db.Transactions.Where(t => t.AccountId == a.Id).Sum(t => (decimal?)(t.Type == TransactionTypes.Income ? t.Amount : -t.Amount))!.Value }).ToListAsync(); return Results.Ok(data); }
    static async Task<IResult> CreateAccount(Guid fundId, MoneyAccountRequest x, FundAccess access, AppDb db) { await access.Require(fundId, Roles.Owner, Roles.Admin); var a = new MoneyAccount { FundId = fundId, Name = x.Name.Trim(), Type = x.Type, InitialBalance = x.InitialBalance, Currency = x.Currency }; db.MoneyAccounts.Add(a); await db.SaveChangesAsync(); return Results.Created($"/api/funds/{fundId}/accounts/{a.Id}", a); }
    static async Task<IResult> UpdateAccount(Guid fundId, Guid id, MoneyAccountRequest x, FundAccess access, AppDb db) { await access.Require(fundId, Roles.Owner, Roles.Admin); var a = await db.MoneyAccounts.SingleOrDefaultAsync(v => v.Id == id && v.FundId == fundId); if (a is null) return Results.NotFound(); a.Name = x.Name.Trim(); a.Type = x.Type; a.InitialBalance = x.InitialBalance; a.Currency = x.Currency; await db.SaveChangesAsync(); return Results.Ok(a); }
    static async Task<IResult> DeleteAccount(Guid fundId, Guid id, FundAccess access, CurrentUser user, AppDb db) { await access.Require(fundId, Roles.Owner, Roles.Admin); var a = await db.MoneyAccounts.SingleOrDefaultAsync(v => v.Id == id && v.FundId == fundId); if (a is null) return Results.NotFound(); if (await db.Transactions.AnyAsync(t => t.AccountId == id)) return Results.Conflict(new { message = "Tài khoản đã có giao dịch; chỉ có thể ẩn." }); SoftDelete(a, user.Id); await db.SaveChangesAsync(); return Results.NoContent(); }

    static async Task<IResult> Transactions(Guid fundId, DateTime? from, DateTime? to, Guid? memberId, Guid? categoryId, string? type, int page = 1, int pageSize = 50, FundAccess access = null!, AppDb db = null!) { await access.Require(fundId); page = Math.Max(1, page); pageSize = Math.Clamp(pageSize == 0 ? 50 : pageSize, 1, 200); var q = db.Transactions.Where(t => t.FundId == fundId); if (from.HasValue) q = q.Where(t => t.TransactionDate >= from); if (to.HasValue) q = q.Where(t => t.TransactionDate <= to); if (memberId.HasValue) q = q.Where(t => t.CreatedBy == memberId); if (categoryId.HasValue) q = q.Where(t => t.CategoryId == categoryId); if (!string.IsNullOrWhiteSpace(type)) q = q.Where(t => t.Type == type); var total = await q.CountAsync(); var items = await q.OrderByDescending(t => t.TransactionDate).ThenByDescending(t => t.CreatedAt).Skip((page - 1) * pageSize).Take(pageSize).Join(db.Users, t => t.CreatedBy, u => u.Id, (t, u) => new { t.Id, t.FundId, t.CategoryId, t.AccountId, t.Type, t.Amount, t.TransactionDate, t.Note, t.Merchant, t.ReceiptUrl, t.CreatedBy, CreatorName = u.DisplayName, t.CreatedAt, t.UpdatedAt }).ToListAsync(); return Results.Ok(new { items, total, page, pageSize }); }
    static async Task<IResult> CreateTransaction(Guid fundId, TransactionRequest x, FundAccess access, CurrentUser user, AppDb db) { await access.Require(fundId, Roles.Owner, Roles.Admin, Roles.Member); var error = await ValidateTransaction(fundId, x, db); if (error is not null) return error; var t = new QuyNhaMinh.Api.Domain.MoneyTransaction { FundId = fundId, CreatedBy = user.Id, CategoryId = x.CategoryId, AccountId = x.AccountId, Type = x.Type, Amount = x.Amount, TransactionDate = x.TransactionDate, Note = x.Note?.Trim() ?? "", Merchant = x.Merchant?.Trim() ?? "", ReceiptUrl = x.ReceiptUrl }; db.Transactions.Add(t); await Audit(db, fundId, user.Id, "create", "transaction", t.Id); await db.SaveChangesAsync(); return Results.Created($"/api/funds/{fundId}/transactions/{t.Id}", t); }
    static async Task<IResult> UpdateTransaction(Guid fundId, Guid id, TransactionRequest x, FundAccess access, CurrentUser user, AppDb db) { var member = await access.Require(fundId, Roles.Owner, Roles.Admin, Roles.Member); var t = await db.Transactions.SingleOrDefaultAsync(v => v.Id == id && v.FundId == fundId); if (t is null) return Results.NotFound(); if (member.Role == Roles.Member && t.CreatedBy != user.Id) throw new ForbiddenException("Thành viên chỉ được sửa giao dịch do mình tạo"); var error = await ValidateTransaction(fundId, x, db); if (error is not null) return error; t.CategoryId = x.CategoryId; t.AccountId = x.AccountId; t.Type = x.Type; t.Amount = x.Amount; t.TransactionDate = x.TransactionDate; t.Note = x.Note?.Trim() ?? ""; t.Merchant = x.Merchant?.Trim() ?? ""; t.ReceiptUrl = x.ReceiptUrl; t.UpdatedAt = DateTimeOffset.UtcNow; await Audit(db, fundId, user.Id, "update", "transaction", t.Id); await db.SaveChangesAsync(); return Results.Ok(t); }
    static async Task<IResult> DeleteTransaction(Guid fundId, Guid id, FundAccess access, CurrentUser user, AppDb db) { var member = await access.Require(fundId, Roles.Owner, Roles.Admin, Roles.Member); var t = await db.Transactions.SingleOrDefaultAsync(v => v.Id == id && v.FundId == fundId); if (t is null) return Results.NotFound(); if (member.Role == Roles.Member && t.CreatedBy != user.Id) throw new ForbiddenException("Thành viên chỉ được xóa giao dịch do mình tạo"); SoftDelete(t, user.Id); await Audit(db, fundId, user.Id, "trash", "transaction", t.Id); await db.SaveChangesAsync(); return Results.NoContent(); }
    static async Task<IResult> Trash(Guid fundId, FundAccess access, AppDb db) { await access.Require(fundId, Roles.Owner, Roles.Admin); return Results.Ok(await db.Transactions.IgnoreQueryFilters().Where(x => x.FundId == fundId && x.IsDeleted).OrderByDescending(x => x.Id).ToListAsync()); }
    static async Task<IResult> Restore(Guid fundId, RestoreRequest x, FundAccess access, AppDb db) { await access.Require(fundId, Roles.Owner, Roles.Admin); var items = await db.Transactions.IgnoreQueryFilters().Where(t => t.FundId == fundId && t.IsDeleted && x.Ids.Contains(t.Id)).ToListAsync(); foreach (var t in items) { t.IsDeleted = false; t.DeletedAt = null; t.DeletedBy = null; } await db.SaveChangesAsync(); return Results.Ok(new { restored = items.Count }); }
    static async Task<IResult> PermanentDelete(Guid fundId, Guid id, FundAccess access, AppDb db) { await access.Require(fundId, Roles.Owner); var t = await db.Transactions.IgnoreQueryFilters().SingleOrDefaultAsync(v => v.Id == id && v.FundId == fundId && v.IsDeleted); if (t is null) return Results.NotFound(); db.Transactions.Remove(t); await db.SaveChangesAsync(); return Results.NoContent(); }

    static async Task<IResult> Budgets(Guid fundId, int year, int month, FundAccess access, AppDb db) { await access.Require(fundId); var start = new DateTime(year, month, 1, 0, 0, 0, DateTimeKind.Utc); var end = start.AddMonths(1); var data = await db.Budgets.Where(b => b.FundId == fundId && b.Year == year && b.Month == month).Select(b => new { b.Id, b.CategoryId, Category = db.Categories.Where(c => c.Id == b.CategoryId).Select(c => c.Name).First(), b.LimitAmount, b.WarningPercent, Spent = db.Transactions.Where(t => t.FundId == fundId && t.CategoryId == b.CategoryId && t.Type == TransactionTypes.Expense && t.TransactionDate >= start && t.TransactionDate < end).Sum(t => (decimal?)t.Amount) ?? 0 }).ToListAsync(); return Results.Ok(data); }
    static async Task<IResult> UpsertBudget(Guid fundId, BudgetRequest x, FundAccess access, AppDb db) { await access.Require(fundId, Roles.Owner, Roles.Admin); var b = await db.Budgets.SingleOrDefaultAsync(v => v.FundId == fundId && v.CategoryId == x.CategoryId && v.Year == x.Year && v.Month == x.Month); if (b is null) { b = new Budget { FundId = fundId, CategoryId = x.CategoryId, Year = x.Year, Month = x.Month }; db.Budgets.Add(b); } b.LimitAmount = x.LimitAmount; b.WarningPercent = x.WarningPercent; await db.SaveChangesAsync(); return Results.Ok(b); }
    static async Task<IResult> DeleteBudget(Guid fundId, Guid id, FundAccess access, AppDb db) { await access.Require(fundId, Roles.Owner, Roles.Admin); var b = await db.Budgets.SingleOrDefaultAsync(v => v.Id == id && v.FundId == fundId); if (b is null) return Results.NotFound(); db.Budgets.Remove(b); await db.SaveChangesAsync(); return Results.NoContent(); }
    static async Task<IResult> Reminders(Guid fundId, FundAccess access, AppDb db) { await access.Require(fundId); return Results.Ok(await db.Reminders.Where(r => r.FundId == fundId).OrderBy(r => r.NextDueAt).ToListAsync()); }
    static async Task<IResult> CreateReminder(Guid fundId, ReminderRequest x, FundAccess access, AppDb db) { await access.Require(fundId, Roles.Owner, Roles.Admin, Roles.Member); var r = new Reminder { FundId = fundId, Title = x.Title.Trim(), ExpectedAmount = x.ExpectedAmount, NextDueAt = x.NextDueAt, Recurrence = x.Recurrence, IsEnabled = x.IsEnabled }; db.Reminders.Add(r); await db.SaveChangesAsync(); return Results.Created($"/api/funds/{fundId}/reminders/{r.Id}", r); }
    static async Task<IResult> UpdateReminder(Guid fundId, Guid id, ReminderRequest x, FundAccess access, AppDb db) { await access.Require(fundId, Roles.Owner, Roles.Admin, Roles.Member); var r = await db.Reminders.SingleOrDefaultAsync(v => v.Id == id && v.FundId == fundId); if (r is null) return Results.NotFound(); r.Title = x.Title.Trim(); r.ExpectedAmount = x.ExpectedAmount; r.NextDueAt = x.NextDueAt; r.Recurrence = x.Recurrence; r.IsEnabled = x.IsEnabled; await db.SaveChangesAsync(); return Results.Ok(r); }
    static async Task<IResult> DeleteReminder(Guid fundId, Guid id, FundAccess access, CurrentUser user, AppDb db) { await access.Require(fundId, Roles.Owner, Roles.Admin); var r = await db.Reminders.SingleOrDefaultAsync(v => v.Id == id && v.FundId == fundId); if (r is null) return Results.NotFound(); SoftDelete(r, user.Id); await db.SaveChangesAsync(); return Results.NoContent(); }

    static async Task<IResult> Dashboard(Guid fundId, int? year, int? month, FundAccess access, AppDb db) { await access.Require(fundId); var now = DateTime.UtcNow; var y = year ?? now.Year; var m = month ?? now.Month; var start = new DateTime(y, m, 1, 0, 0, 0, DateTimeKind.Utc); var end = start.AddMonths(1); var previousStart = start.AddMonths(-1); var q = db.Transactions.Where(t => t.FundId == fundId && t.TransactionDate >= start && t.TransactionDate < end); var income = await q.Where(t => t.Type == TransactionTypes.Income).SumAsync(t => (decimal?)t.Amount) ?? 0; var expense = await q.Where(t => t.Type == TransactionTypes.Expense).SumAsync(t => (decimal?)t.Amount) ?? 0; var todayStart = now.Date; var todayExpense = await q.Where(t => t.Type == TransactionTypes.Expense && t.TransactionDate >= todayStart).SumAsync(t => (decimal?)t.Amount) ?? 0; var previous = db.Transactions.Where(t => t.FundId == fundId && t.TransactionDate >= previousStart && t.TransactionDate < start); var previousIncome = await previous.Where(t => t.Type == TransactionTypes.Income).SumAsync(t => (decimal?)t.Amount) ?? 0; var previousExpense = await previous.Where(t => t.Type == TransactionTypes.Expense).SumAsync(t => (decimal?)t.Amount) ?? 0; var categories = await q.Where(t => t.Type == TransactionTypes.Expense).GroupBy(t => t.CategoryId).Select(g => new { categoryId = g.Key, amount = g.Sum(t => t.Amount) }).Join(db.Categories, x => x.categoryId, c => c.Id, (x, c) => new { c.Name, c.Color, x.amount }).OrderByDescending(x => x.amount).ToListAsync(); var days = await q.GroupBy(t => t.TransactionDate.Date).Select(g => new { date = g.Key, income = g.Where(t => t.Type == TransactionTypes.Income).Sum(t => t.Amount), expense = g.Where(t => t.Type == TransactionTypes.Expense).Sum(t => t.Amount) }).OrderBy(x => x.date).ToListAsync(); return Results.Ok(new { income, expense, balance = income - expense, todayExpense, monthExpense = expense, previousIncome, previousExpense, incomeChangePercent = Percent(income, previousIncome), expenseChangePercent = Percent(expense, previousExpense), categories, days }); }
    static async Task<IResult> Report(Guid fundId, DateTime from, DateTime to, Guid? memberId, Guid? categoryId, FundAccess access, AppDb db) {
        await access.Require(fundId);
        var q = db.Transactions.Where(t => t.FundId == fundId && t.TransactionDate >= from && t.TransactionDate < to);
        if (memberId.HasValue) q = q.Where(t => t.CreatedBy == memberId.Value);
        if (categoryId.HasValue) q = q.Where(t => t.CategoryId == categoryId.Value);
        var income = await q.Where(t => t.Type == TransactionTypes.Income).SumAsync(t => (decimal?)t.Amount) ?? 0;
        var expense = await q.Where(t => t.Type == TransactionTypes.Expense).SumAsync(t => (decimal?)t.Amount) ?? 0;
        var byCategory = await q.GroupBy(t => new { t.CategoryId, t.Type })
            .Select(g => new { g.Key.CategoryId, g.Key.Type, Amount = g.Sum(x => x.Amount), Count = g.Count() })
            .Join(db.Categories, x => x.CategoryId, c => c.Id, (x, c) => new { c.Id, c.Name, c.Color, x.Type, x.Amount, x.Count })
            .OrderByDescending(x => x.Amount).ToListAsync();
        var byMember = await q.GroupBy(t => t.CreatedBy)
            .Select(g => new { UserId = g.Key, Amount = g.Sum(x => x.Type == TransactionTypes.Income ? x.Amount : -x.Amount), Count = g.Count() })
            .Join(db.Users, x => x.UserId, u => u.Id, (x, u) => new { x.UserId, u.DisplayName, x.Amount, x.Count })
            .OrderByDescending(x => x.Count).ToListAsync();
        var byDay = await q.GroupBy(t => t.TransactionDate.Date)
            .Select(g => new { Date = g.Key, Income = g.Where(x => x.Type == TransactionTypes.Income).Sum(x => x.Amount), Expense = g.Where(x => x.Type == TransactionTypes.Expense).Sum(x => x.Amount) })
            .OrderBy(x => x.Date).ToListAsync();
        return Results.Ok(new { from, to, income, expense, balance = income - expense, byCategory, byMember, byDay });
    }

    static async Task<IResult?> ValidateTransaction(Guid fundId, TransactionRequest x, AppDb db) { if (x.Amount <= 0 || !new[] { TransactionTypes.Income, TransactionTypes.Expense }.Contains(x.Type)) return Results.BadRequest(new { message = "Số tiền hoặc loại giao dịch không hợp lệ." }); if (!await db.Categories.AnyAsync(c => c.Id == x.CategoryId && c.FundId == fundId && c.Type == x.Type)) return Results.BadRequest(new { message = "Danh mục không hợp lệ." }); if (!await db.MoneyAccounts.AnyAsync(a => a.Id == x.AccountId && a.FundId == fundId)) return Results.BadRequest(new { message = "Tài khoản tiền không hợp lệ." }); return null; }
    static void SoftDelete(ISoftDelete x, Guid userId) { x.IsDeleted = true; x.DeletedAt = DateTimeOffset.UtcNow; x.DeletedBy = userId; }
    static Task Audit(AppDb db, Guid fundId, Guid userId, string action, string entity, Guid id) { db.AuditLogs.Add(new AuditLog { FundId = fundId, UserId = userId, Action = action, EntityType = entity, EntityId = id }); return Task.CompletedTask; }
    static decimal Percent(decimal current, decimal previous) => previous == 0 ? (current == 0 ? 0 : 100) : Math.Round((current - previous) / previous * 100, 1);
}
